stages:
  - build
  - test
  - publish

.build:
  stage: build
  variables:
    ARCH: armv7hl
    SFOS_VERSION: "3.4.0.24"
    SYNCTHING_VERSION: "1.17.0"
    SYNCTHING_ARCH: arm
  image: coderus/sailfishos-platform-sdk:${SFOS_VERSION}
  artifacts:
    paths:
      - "output/*"
  script:
    - mkdir output
    - mkdir ~/build
    - cp -r * ~/build
    - curl -LO https://github.com/syncthing/syncthing/releases/download/v${SYNCTHING_VERSION}/syncthing-linux-${SYNCTHING_ARCH}-v${SYNCTHING_VERSION}.tar.gz
    - tar xf syncthing-linux-${SYNCTHING_ARCH}-v${SYNCTHING_VERSION}.tar.gz
    - mv syncthing-linux-${SYNCTHING_ARCH}-v${SYNCTHING_VERSION}/syncthing ~/build/rpm
    - pushd ~/build
    - mb2 -t SailfishOS-$SFOS_VERSION-$ARCH build
    - popd
    - cp -v ~/build/RPMS/* output
  only:
    - merge_requests
    - tags

build_armv7hl:
  extends: .build

build_i486:
  extends: .build
  variables:
    ARCH: i486
    SYNCTHING_ARCH: "386"

build_aarch64:
  extends: .build
  variables:
    ARCH: aarch64
    SYNCTHING_ARCH: arm64

test:validate-rpms:
  stage: test
  image: registry.gitlab.com/whisperfish/sailo-rs/rpm-validator:latest
  allow_failure: true
  needs:
    - build_armv7hl
    - build_i486
    - build_aarch64
  script:
    - rpmvalidation.sh output/*.rpm
  only:
    - merge_requests
    - tags

publish:
  image: inetprocess/gitlab-release
  stage: publish
  needs:
    - build_armv7hl
    - build_i486
    - build_aarch64
  only:
    - tags
  script:
    - gitlab-release --message 'Release $CI_COMMIT_TAG' output/*
